"""add interview_acquisition to experiences

Revision ID: 09b11a46dc78
Revises: 9f2b3c4d5e6f
Create Date: 2026-02-14 23:15:20.353453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b11a46dc78'
down_revision: Union[str, Sequence[str], None] = '9f2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('companies_name_unique'), 'companies', type_='unique')
    op.create_index(op.f('ix_company_requests_id'), 'company_requests', ['id'], unique=False)
    op.add_column('experiences', sa.Column('interview_acquisition', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiences', 'interview_acquisition')
    op.drop_index(op.f('ix_company_requests_id'), table_name='company_requests')
    op.create_unique_constraint(op.f('companies_name_unique'), 'companies', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
