"""add design teams and reviews

Revision ID: 3d34af11d1d8
Revises: 09b11a46dc78
Create Date: 2026-02-16 20:59:00.491479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3d34af11d1d8"
down_revision: Union[str, Sequence[str], None] = "09b11a46dc78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "design_teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("categories", sa.ARRAY(sa.String(length=100)), nullable=False),
        sa.Column("website_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_design_teams_id"), "design_teams", ["id"], unique=False)
    op.create_table(
        "design_team_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("design_team_id", sa.Integer(), nullable=False),
        sa.Column("submitter_email", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=255), nullable=False),
        sa.Column("term", sa.String(length=50), nullable=False),
        sa.Column("time_commitment", sa.String(length=100), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tips", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["design_team_id"],
            ["design_teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_design_team_reviews_id"), "design_team_reviews", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_design_team_reviews_id"), table_name="design_team_reviews")
    op.drop_table("design_team_reviews")
    op.drop_index(op.f("ix_design_teams_id"), table_name="design_teams")
    op.drop_table("design_teams")
    # ### end Alembic commands ###
