"""Update program enum to use string values

Revision ID: 7c5b682eb2a7
Revises: 1e9f4f206db1
Create Date: 2026-02-02 22:08:43.637524

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7c5b682eb2a7"
down_revision: Union[str, Sequence[str], None] = "1e9f4f206db1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
