"""refactor design team reviews to application experiences

Revision ID: 83744fe2430a
Revises: 3d34af11d1d8
Create Date: 2026-02-17 12:30:05.454753

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "83744fe2430a"
down_revision: Union[str, Sequence[str], None] = "3d34af11d1d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "design_team_reviews",
        sa.Column("position", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "design_team_reviews", sa.Column("accepted", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "design_team_reviews", sa.Column("difficulty", sa.Integer(), nullable=False)
    )
    op.add_column(
        "design_team_reviews",
        sa.Column("interview_acquisition", sa.String(length=500), nullable=True),
    )
    op.drop_column("design_team_reviews", "rating")
    op.drop_column("design_team_reviews", "time_commitment")
    op.drop_column("design_team_reviews", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "design_team_reviews",
        sa.Column("role", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.add_column(
        "design_team_reviews",
        sa.Column(
            "time_commitment",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "design_team_reviews",
        sa.Column("rating", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("design_team_reviews", "interview_acquisition")
    op.drop_column("design_team_reviews", "difficulty")
    op.drop_column("design_team_reviews", "accepted")
    op.drop_column("design_team_reviews", "position")
    # ### end Alembic commands ###
