"""add user model and restructure experience

Revision ID: a0efdc136687
Revises: 1ee1a9f4ea33
Create Date: 2026-01-15 13:57:03.241870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0efdc136687'
down_revision: Union[str, Sequence[str], None] = '1ee1a9f4ea33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('program', sa.Enum('SOFTWARE', 'ELECTRICAL', 'COMPUTER', 'MECHANICAL', 'MECHATRONICS', 'CIVIL', 'CHEMICAL', 'MATERIALS', 'ENGINEERING_PHYSICS', name='program'), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('companies', sa.Column('industries', sa.ARRAY(sa.String(length=100)), nullable=False))
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_column('companies', 'industry')
    op.drop_column('companies', 'review_count')
    op.add_column('experiences', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('experiences', sa.Column('position', sa.String(length=255), nullable=False))
    op.add_column('experiences', sa.Column('term', sa.String(length=50), nullable=False))
    op.add_column('experiences', sa.Column('offer_received', sa.Boolean(), nullable=False))
    op.add_column('experiences', sa.Column('difficulty', sa.Integer(), nullable=False))
    op.add_column('experiences', sa.Column('stages', sa.JSON(), nullable=False))
    op.add_column('experiences', sa.Column('tips', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'experiences', 'users', ['user_id'], ['id'])
    op.drop_column('experiences', 'title')
    op.drop_column('experiences', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('experiences', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'experiences', type_='foreignkey')
    op.drop_column('experiences', 'tips')
    op.drop_column('experiences', 'stages')
    op.drop_column('experiences', 'difficulty')
    op.drop_column('experiences', 'offer_received')
    op.drop_column('experiences', 'term')
    op.drop_column('experiences', 'position')
    op.drop_column('experiences', 'user_id')
    op.add_column('companies', sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.drop_column('companies', 'industries')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
