"""add new_company_name to experiences

Revision ID: cc2395f4bbc9
Revises: 1d3c72ae95eb
Create Date: 2026-02-24 14:27:11.697485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc2395f4bbc9'
down_revision: Union[str, Sequence[str], None] = '1d3c72ae95eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('new_company_name', sa.String(length=255), nullable=True))
    op.alter_column('experiences', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experiences', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('experiences', 'new_company_name')
    # ### end Alembic commands ###
